<?php use Snowdog\Academy\Model\Book;

require_once(__DIR__ . '/../../common/header.phtml');

$action = '/admin/new_book';
if ($this->book instanceof Book) {
    $title = $this->book->getTitle();
    $author = $this->book->getAuthor();
    $isbn = $this->book->getIsbn();
    $adult_only = $this->book->isAdultOnly();
    $action = '/admin/edit_book/' . $this->book->getId();
}
?>
<section id="add" class="padded">
    <a href="/admin/new_book_csv" class="btn btn-primary">Add books from csv file</a>
</section>
<section id="new-book-form" class="padded">
    <form class="form-horizontal" method="POST" action="<?= $action ?>">
        <div class="form-group">
            <label for="book-title" class="col-sm-1 control-label">Title:</label>
            <div class="col-sm-10">
                <input type="text" id="book-title" name="title" class="form-control" value="<?= $title ?? $_POST['title'] ?? ''?>" />
            </div>
        </div>
        <div class="form-group">
            <label for="author" class="col-sm-1 control-label">Author:</label>
            <div class="col-sm-10">
                <input type="text" id="author" name="author" class="form-control" value="<?= $author ?? $_POST['author'] ?? ''?>" />
            </div>
        </div>
        <div class="form-group">
            <label for="isbn" class="col-sm-1 control-label">ISBN:</label>
            <div class="col-sm-10">
                <input type="text" id="isbn" name="isbn" class="form-control" value="<?= $isbn ?? $_POST['isbn'] ??''?>" />
                <button type="submit" id="search-button"class="btn btn-primary" name="submit2" disabled=true>Search in Google API</button>
            </div>
        </div>
        <div class="form-group">
            <label for="adult_only" class="col-sm-1 control-label">Is only for adults:</label>
            <div class="col-sm-10"> 
                <input type="checkbox" id="adult_only" name="adult_only" class="form-control" <?= $adult_only ??isset($_POST['adult_only'])?'checked':'' ?> />
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-1 col-sm-2">
                <button type="submit" class="btn btn-primary" name="submit">Save book</button>
            </div>
        </div>
    </form>
</section>
<script>
    document.getElementById('isbn').addEventListener('input',e=>e.target.value?document.getElementById('search-button').disabled=false:document.getElementById('search-button').disabled=true)
</script>
<?php require_once(__DIR__ . '/../../common/footer.phtml'); ?>
